---
  # These are the dependencies for the gateway. The Red Hat solution uses dm-multipath as part of a
  # strategy to eliminate stale I/O when data paths are lost. Targetcli provides an interface to the
  # LIO configuration to check what's been done!
  - name: Check required rpms are installed
    yum: name={{ item.rpm }} state=latest
    with_items:
      - rpm: tcmu-runner
      - rpm: ceph-iscsi-config
      - rpm: targetcli
      - rpm: ceph-common

  - name: check the status of the target.service override
    stat: path=/etc/systemd/system/target.service
    register: target

  - name: Mask the target service - preventing manual start
    shell: systemctl disable target.service && systemctl mask target.service
    when: target.stat.exists == False or (target.stat.exists and target.stat.islnk == False)

  - name: Enable the rbd-target-gw service and make sure it's running
    service: name=rbd-target-gw enabled=yes state=started

